# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: application

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.1
      import:
        name-allowlist:
          - mcuboot
          - mbedtls
          - trusted-firmware-m
          - open-amp
          - libmetal
          - cmsis
          - cmsis_6
          - tinycbor
          - zcbor
          - oberon-psa-crypto
          - segger
          - fatfs
          - cmsis_6
          - hal_nxp 
